### ISSUE TITLE
Add an option to pass arguments

### ISSUE THREAD

**Issue by developomp** [zachmatson/svelte-check-plugin#1]
Example:
```js
new SvelteCheckPlugin({
    args: "--ignore sub_project/node_mpdules --fail-on-hints"
}),
```

**Comment by zachmatson** [comment]
Thanks for this suggestion! It's exciting to see people getting use out of this plugin. I should be able to add this feature soon.

Would it affect the usability much if the syntax was like this?
```javascript
new SvelteCheckPlugin({
    args: ["--ignore", "sub_project/node_mpdules", "--fail-on-hints"]
}),
```

This would probably be more reliable than trying to emulate some kind of shell parsing behavior manually and more portable than using an actual shell to spawn `svelte-check`.

**Comment by developomp** [comment]
> Would it affect the usability much if the syntax was like this?

No, not at all. That works perfectly fine too.

**Comment by zachmatson** [comment]
Should work now for v1.0.3. Thanks for using the plugin and for your feedback!
